%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: \\acad-filebox\u_drive\900334684\AD-Profile\Downloads\P2\project2data.csv
%
% Auto-generated by MATLAB on 28-Oct-2019 19:41:35

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Age", "TotalNumber", "NumberofFemales", "NumberofMales", "VarName1", "Age1", "TotalNumber1", "NumberofFemales1", "NumberofMales1"];
opts.VariableTypes = ["double", "double", "double", "double", "string", "double", "double", "double", "double"];
opts = setvaropts(opts, 5, "WhitespaceRule", "preserve");
opts = setvaropts(opts, 5, "EmptyFieldRule", "auto");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
%tbl = readtable("\\acad-filebox\u_drive\900334684\AD-Profile\Downloads\P2\project2data.csv", opts);
%tbl = readtable("C:\Users\900334684\Dropbox\430\p2\project2data.csv", opts);
tbl = readtable("project2data.csv", opts);

%% Convert to output type
Age = tbl.Age;
TotalNumber = tbl.TotalNumber;
NumberofFemales = tbl.NumberofFemales;
NumberofMales = tbl.NumberofMales;
VarName1 = tbl.VarName1;
Age1 = tbl.Age1;
TotalNumber1 = tbl.TotalNumber1;
NumberofFemales1 = tbl.NumberofFemales1;
NumberofMales1 = tbl.NumberofMales1;

%% Clear temporary variables
clear opts tbl